// Irradiant Uranium
recipes.remove(<advanced_solar_panels:crafting:3>);
recipes.addShaped(<advanced_solar_panels:crafting:3> * 1, [[<ic2:casing:2>, <ic2:dust:6>, <ic2:casing:2>], [<minecraft:glowstone_dust>, <ore:ingotUranium>, <minecraft:glowstone_dust>],[<ic2:casing:2>, <ic2:dust:6>, <ic2:casing:2>]]);

// Modularium
recipes.remove(<modularmachinery:itemmodularium>);
recipes.addShaped(<modularmachinery:itemmodularium> * 1, [[<moreplates:bronze_stick>, <moreplates:bronze_stick>, <moreplates:bronze_stick>], [<advanced_solar_panels:crafting:3>, <psi:material:1>, <advanced_solar_panels:crafting:3>],[<moreplates:bronze_stick>, <moreplates:bronze_stick>, <moreplates:bronze_stick>]]);

// Infinity multi tool
recipes.remove(<avaritia_neutronium_addon:infinitymultitoolre>);
mods.avaritia.ExtremeCrafting.addShaped("NAMEPLJJJAACEHOLDER", <avaritia_neutronium_addon:infinitymultitoolre> * 1, [[null, null, null, null, null, null, null, null, null], [null, <avaritia:infinity_shovel>, <additional_addons:chaoticinfinityingot>, <avaritia:infinity_axe>, <additional_addons:chaoticinfinityingot>, <avaritia:infinity_hoe>, <additional_addons:chaoticinfinityingot>, <avaritia:infinity_pickaxe>, null],[null, null, null, null, <additional_addons:chaoticinfinityingot>, null, null, null, null],[null, null, null, null, <additional_addons:chaoticinfinityingot>, null, null, null, null],[null, null, null, null, <avaritia:infinity_sword>, null, null, null, null],[null, null, null, null, <additional_addons:chaoticinfinityingot>, null, null, null, null],[null, null, null, null, <additional_addons:chaoticinfinityingot>, null, null, null, null],[null, null, null, null, <additional_addons:chaoticinfinityingot>, null, null, null, null],[null, null, null, null, <additional_addons:chaoticinfinityingot>, null, null, null, null]]);

// Neutronium crystal
recipes.remove(<avaritia_neutronium_addon:neutroniumcrystal>);
mods.avaritia.ExtremeCrafting.addShaped("NAMEPLACEHOLDWAGERER", <avaritia_neutronium_addon:neutroniumcrystal> * 1, [[null, null, null, null, <mysticalagradditions:special:5>, null, null, null, null], [null, null, null, <avaritia:resource:4>, <avaritia_neutronium_addon:neutroniumunstableblockr>, <avaritia:resource:4>, null, null, null],[null, null, <avaritia:resource:4>, <mysticalagradditions:special:5>, <avaritia_neutronium_addon:neutroniumunstableblockr>, <mysticalagradditions:special:5>, <avaritia:resource:4>, null, null],[null, null, <avaritia:resource:4>, <ic2:iridium_reflector>, <moreplates:neutronium_plate>, <ic2:iridium_reflector>, <avaritia:resource:4>, null, null],[null, null, <avaritia:resource:4>, <ic2:iridium_reflector>, <avaritiaio:grindingballneutronium>, <ic2:iridium_reflector>, <avaritia:resource:4>, null, null],[null, null, <avaritia:resource:4>, <ic2:iridium_reflector>, <moreplates:neutronium_plate>, <ic2:iridium_reflector>, <avaritia:resource:4>, null, null],[null, null, <avaritia:resource:4>, <mysticalagradditions:special:5>, <avaritia_neutronium_addon:neutroniumunstableblockr>, <mysticalagradditions:special:5>, <avaritia:resource:4>, null, null],[null, null, null, <avaritia:resource:4>, <avaritia_neutronium_addon:neutroniumunstableblockr>, <avaritia:resource:4>, null, null, null],[null, null, null, null, <mysticalagradditions:special:5>, null, null, null, null]]);

// Neutronium unstable sword
recipes.remove(<avaritia_neutronium_addon:neutroniumunstablesword>);
mods.avaritia.ExtremeCrafting.addShaped("NAWAGGAHMEPLACEHOLDER", <avaritia_neutronium_addon:neutroniumunstablesword> * 1, [[null, null, null, null, null, null, null, <moreplates:neutronium_plate>, <moreplates:neutronium_plate>], [null, null, null, null, null, null, <moreplates:neutronium_plate>, <ic2:iridium_reflector>, <moreplates:neutronium_plate>],[null, null, null, null, null, <moreplates:neutronium_plate>, <ic2:iridium_reflector>, <moreplates:neutronium_plate>, null],[null, null, null, null, <moreplates:neutronium_plate>, <ic2:iridium_reflector>, <moreplates:neutronium_plate>, null, null],[null, <avaritiaio:grindingballneutronium>, null, <moreplates:neutronium_plate>, <ic2:iridium_reflector>, <moreplates:neutronium_plate>, null, null, null],[null, null, <avaritia:resource:4>, <ic2:iridium_reflector>, <moreplates:neutronium_plate>, null, null, null, null],[null, <moreplates:neutronium_plate>, <mysticalagradditions:special:5>, <avaritia:resource:4>, null, null, null, null, null],[null, <moreplates:neutronium_plate>, <moreplates:neutronium_plate>, null, <avaritiaio:grindingballneutronium>, null, null, <ic2:iridium_reflector>, null],[<avaritia_neutronium_addon:neutroniumcrystal>, null, null, null, null, null, null, null, null]]);

// Neutronium unstable pickaxe
recipes.remove(<avaritia_neutronium_addon:neutroniumunstablepickaxe>);
mods.avaritia.ExtremeCrafting.addShaped("NAMEPLAHAWAWCEHOLDER", <avaritia_neutronium_addon:neutroniumunstablepickaxe> * 1, [[null, <moreplates:neutronium_plate>, <moreplates:neutronium_plate>, <moreplates:neutronium_plate>, <moreplates:neutronium_plate>, <moreplates:neutronium_plate>, <moreplates:neutronium_plate>, <moreplates:neutronium_plate>, null], [<moreplates:neutronium_plate>, <moreplates:neutronium_plate>, <moreplates:neutronium_plate>, <moreplates:neutronium_plate>, <avaritia_neutronium_addon:neutroniumcrystal>, <moreplates:neutronium_plate>, <moreplates:neutronium_plate>, <moreplates:neutronium_plate>, <moreplates:neutronium_plate>],[<moreplates:neutronium_plate>, <moreplates:neutronium_plate>, null, null, <avaritia_neutronium_addon:neutroniumunstableblockr>, null, null, <moreplates:neutronium_plate>, <moreplates:neutronium_plate>],[null, null, null, null, <avaritia_neutronium_addon:neutroniumunstableblockr>, null, null, null, null],[null, null, null, null, <avaritia_neutronium_addon:neutroniumunstableblockr>, null, null, null, null],[null, null, null, null, <avaritia_neutronium_addon:neutroniumunstableblockr>, null, null, null, null],[null, null, null, null, <avaritia_neutronium_addon:neutroniumunstableblockr>, null, null, null, null],[null, null, null, null, <avaritia_neutronium_addon:neutroniumunstableblockr>, null, null, null, null],[null, null, null, null, <avaritia_neutronium_addon:neutroniumunstableblockr>, null, null, null, null]]);

// Neutronium unstable axe
recipes.remove(<avaritia_neutronium_addon:neutroniumunstableaxe>);
mods.avaritia.ExtremeCrafting.addShaped("NAMEPLHWEATEACEHOLDER", <avaritia_neutronium_addon:neutroniumunstableaxe> * 1, [[null, null, null, <avaritia:resource:4>, null, null, null, null, null], [null, null, <avaritia:resource:4>, <avaritia:resource:4>, <avaritia:resource:4>, <avaritia:resource:4>, <avaritia:resource:4>, null, null],[null, null, null, <avaritia:resource:4>, <avaritia:resource:4>, <avaritia:resource:4>, <avaritia:resource:4>, null, null],[null, null, null, null, null, <avaritia:resource:4>, <avaritia_neutronium_addon:neutroniumcrystal>, null, null],[null, null, null, null, null, null, <moreplates:neutronium_plate>, null, null],[null, null, null, null, null, null, <moreplates:neutronium_plate>, null, null],[null, null, null, null, null, null, <moreplates:neutronium_plate>, null, null],[null, null, null, null, null, null, <moreplates:neutronium_plate>, null, null],[null, null, null, null, null, null, <moreplates:neutronium_plate>, null, null]]);

// Neutronium unstable shovel
recipes.remove(<avaritia_neutronium_addon:neutroniumunstableshovel>);
mods.avaritia.ExtremeCrafting.addShaped("NAMEPLACJERTAEHOLDER", <avaritia_neutronium_addon:neutroniumunstableshovel> * 1, [[null, null, null, null, null, null, <moreplates:neutronium_plate>, <moreplates:neutronium_plate>, <moreplates:neutronium_plate>], [null, null, null, null, null, <moreplates:neutronium_plate>, <moreplates:neutronium_plate>, <avaritia_neutronium_addon:neutroniumcrystal>, <moreplates:neutronium_plate>],[null, null, null, null, null, null, <moreplates:neutronium_plate>, <moreplates:neutronium_plate>, <moreplates:neutronium_plate>],[null, null, null, null, null, <avaritia:resource:4>, null, <moreplates:neutronium_plate>, null],[null, null, null, null, <avaritia:resource:4>, null, null, null, null],[null, null, null, <avaritia:resource:4>, null, null, null, null, null],[null, null, <avaritia:resource:4>, null, null, null, null, null, null],[null, <avaritia:resource:4>, null, null, null, null, null, null, null],[<mysticalagradditions:special:5>, null, null, null, null, null, null, null, null]]);

// Neutronium unstable bow
recipes.remove(<avaritia_neutronium_addon:neutroniumunstablebow>);
mods.avaritia.ExtremeCrafting.addShaped("NAMEPLACEJIWAHOLDER", <avaritia_neutronium_addon:neutroniumunstablebow> * 1, [[null, null, null, <moreplates:neutronium_plate>, <moreplates:neutronium_plate>, null, null, null, null], [null, null, <moreplates:neutronium_plate>, null, <avaritia:resource:4>, null, null, null, null],[null, <moreplates:neutronium_plate>, null, null, <avaritia:resource:4>, null, null, null, null],[<moreplates:neutronium_plate>, null, null, null, <avaritia:resource:4>, null, null, null, null],[<avaritia_neutronium_addon:neutroniumcrystal>, null, null, null, <avaritia:resource:4>, null, null, null, null],[<moreplates:neutronium_plate>, null, null, null, <avaritia:resource:4>, null, null, null, null],[null, <moreplates:neutronium_plate>, null, null, <avaritia:resource:4>, null, null, null, null],[null, null, <moreplates:neutronium_plate>, null, <avaritia:resource:4>, null, null, null, null],[null, null, null, <moreplates:neutronium_plate>, <moreplates:neutronium_plate>, null, null, null, null]]);

// Neutronium crystal
recipes.remove(<avaritia_neutronium_addon:neutroniumcrystalleveltwo>);
mods.avaritia.ExtremeCrafting.addShaped("NAMEPLACHAWEHOLDER", <avaritia_neutronium_addon:neutroniumcrystalleveltwo> * 1, [[null, null, null, null, null, null, null, null, null], [null, null, null, null, <avaritia_neutronium_addon:neutroniumstarre>, null, null, null, null],[null, null, null, <avaritia:resource:4>, <avaritia_neutronium_addon:neutroniumunstableingot>, <avaritia:resource:4>, null, null, null],[null, null, null, <avaritia:resource:4>, <avaritia:block_resource:0>, <avaritia:resource:4>, null, null, null],[null, null, null, <avaritia_neutronium_addon:neutroniumunstableingot>, <avaritia_neutronium_addon:neutroniumcrystal>, <avaritia_neutronium_addon:neutroniumunstableingot>, null, null, null],[null, null, null, <avaritia:resource:4>, <avaritia:block_resource:0>, <avaritia:resource:4>, null, null, null],[null, null, null, <avaritia:resource:4>, <avaritia_neutronium_addon:neutroniumunstableingot>, <avaritia:resource:4>, null, null, null],[null, null, null, null, <avaritia_neutronium_addon:neutroniumstarre>, null, null, null, null],[null, null, null, null, null, null, null, null, null]]);

// Neutronium sword
recipes.remove(<avaritia_neutronium_addon:neutroniumsword>);
recipes.addShaped(<avaritia_neutronium_addon:neutroniumsword> * 1, [[null, <avaritia_neutronium_addon:neutroniumcrystalleveltwo>, null], [<avaritia_neutronium_addon:neutroniumcrystalleveltwo>, <avaritia_neutronium_addon:neutroniumunstablesword>, <avaritia_neutronium_addon:neutroniumcrystalleveltwo>],[null, <avaritia_neutronium_addon:neutroniumcrystalleveltwo>, null]]);

// Neutronium shovel
recipes.remove(<avaritia_neutronium_addon:neutroniumshovel>);
recipes.addShaped(<avaritia_neutronium_addon:neutroniumshovel> * 1, [[null, <avaritia_neutronium_addon:neutroniumcrystalleveltwo>, null], [<avaritia_neutronium_addon:neutroniumcrystalleveltwo>, <avaritia_neutronium_addon:neutroniumunstableshovel>, <avaritia_neutronium_addon:neutroniumcrystalleveltwo>],[null, <avaritia_neutronium_addon:neutroniumcrystalleveltwo>, null]]);

// Neutronium axe
recipes.remove(<avaritia_neutronium_addon:neutroniumaxe>);
recipes.addShaped(<avaritia_neutronium_addon:neutroniumaxe> * 1, [[null, <avaritia_neutronium_addon:neutroniumcrystalleveltwo>, null], [<avaritia_neutronium_addon:neutroniumcrystalleveltwo>, <avaritia_neutronium_addon:neutroniumunstableaxe>, <avaritia_neutronium_addon:neutroniumcrystalleveltwo>],[null, <avaritia_neutronium_addon:neutroniumcrystalleveltwo>, null]]);

// Neutronium pickaxe
recipes.remove(<avaritia_neutronium_addon:neutroniumpickaxen>);
recipes.addShaped(<avaritia_neutronium_addon:neutroniumpickaxen> * 1, [[null, <avaritia_neutronium_addon:neutroniumcrystalleveltwo>, null], [<avaritia_neutronium_addon:neutroniumcrystalleveltwo>, <avaritia_neutronium_addon:neutroniumunstablepickaxe>, <avaritia_neutronium_addon:neutroniumcrystalleveltwo>],[null, <avaritia_neutronium_addon:neutroniumcrystalleveltwo>, null]]);

// Neutronium bow
recipes.remove(<avaritia_neutronium_addon:neutroniumbow>);
recipes.addShaped(<avaritia_neutronium_addon:neutroniumbow> * 1, [[null, <avaritia_neutronium_addon:neutroniumcrystalleveltwo>, null], [<avaritia_neutronium_addon:neutroniumcrystalleveltwo>, <avaritia_neutronium_addon:neutroniumunstablebow>, <avaritia_neutronium_addon:neutroniumcrystalleveltwo>],[null, <avaritia_neutronium_addon:neutroniumcrystalleveltwo>, null]]);

// Neutronium multi tool
recipes.remove(<avaritia_neutronium_addon:neutroniummultitoolleveltwo>);
mods.avaritia.ExtremeCrafting.addShaped("NAMEPHHHAWLACEHOLDER", <avaritia_neutronium_addon:neutroniummultitoolleveltwo> * 1, [[null, null, null, null, null, null, null, null, null], [null, <avaritia_neutronium_addon:neutroniumshovel>, <avaritia_neutronium_addon:neutroniumstarre>, <avaritia_neutronium_addon:neutroniumstarre>, <avaritia_neutronium_addon:neutroniumaxe>, <avaritia_neutronium_addon:neutroniumstarre>, <avaritia_neutronium_addon:neutroniumstarre>, <avaritia_neutronium_addon:neutroniumpickaxen>, null],[null, null, null, null, <avaritia_neutronium_addon:neutroniumunstableingot>, null, null, null, null],[null, null, null, null, <avaritia_neutronium_addon:neutroniumunstableingot>, null, null, null, null],[null, null, null, null, <avaritia_neutronium_addon:neutroniumunstableingot>, null, null, null, null],[null, null, null, null, <avaritia_neutronium_addon:neutroniumsword>, null, null, null, null],[null, null, null, null, <avaritia_neutronium_addon:neutroniumunstableingot>, null, null, null, null],[null, null, null, null, <avaritia_neutronium_addon:neutroniumunstableingot>, null, null, null, null],[null, null, null, null, <avaritia_neutronium_addon:neutroniumcrystalleveltwo>, null, null, null, null]]);



// neutronium unstable ingot
recipes.remove(<avaritia_neutronium_addon:neutroniumunstableingot>);
mods.avaritia.ExtremeCrafting.addShaped("NAMEPLAHAWGCEHOLDER", <avaritia_neutronium_addon:neutroniumunstableingot> * 1, [[<avaritia:resource:4>, <avaritia:resource:4>, <avaritia:resource:4>, <avaritia:resource:4>, <avaritia:resource:4>, <avaritia:resource:4>, <avaritia:resource:4>, <avaritia:resource:4>, <avaritia:resource:4>], [<avaritia:resource:4>, <avaritia_neutronium_addon:neutroniumunstableblockr>, <avaritia:block_resource:0>, <avaritia:block_resource:0>, <avaritia_neutronium_addon:neutroniumunstableblockr>, <avaritia:block_resource:0>, <avaritia:block_resource:0>, <avaritia_neutronium_addon:neutroniumunstableblockr>, <avaritia:resource:4>],[<avaritia:resource:4>, <avaritia:block_resource:0>, <avaritia_neutronium_addon:neutroniumunstableblockr>, <avaritia_neutronium_addon:neutroniumunstableblockr>, <avaritia:block_resource:0>, <avaritia_neutronium_addon:neutroniumunstableblockr>, <avaritia_neutronium_addon:neutroniumunstableblockr>, <avaritia:block_resource:0>, <avaritia:resource:4>],[<avaritia:resource:4>, <avaritia_neutronium_addon:neutroniumunstableblockr>, <avaritia:block_resource:0>, <avaritia:block_resource:0>, <avaritia_neutronium_addon:neutroniumunstableblockr>, <avaritia:block_resource:0>, <avaritia:block_resource:0>, <avaritia_neutronium_addon:neutroniumunstableblockr>, <avaritia:resource:4>],[<avaritia:resource:4>, <avaritia:resource:4>, <avaritia:resource:4>, <avaritia:resource:4>, <avaritia:resource:4>, <avaritia:resource:4>, <avaritia:resource:4>, <avaritia:resource:4>, <avaritia:resource:4>],[null, null, null, null, null, null, null, null, null],[null, null, null, null, null, null, null, null, null],[null, null, null, null, null, null, null, null, null],[null, null, null, null, null, null, null, null, null]]);

// Chaotic Ingot
recipes.remove(<additional_addons:chaoticingot>);
mods.avaritia.ExtremeCrafting.addShaped("NAHHAWMEPLACEHOLDER", <additional_addons:chaoticingot> * 1, [[<draconicevolution:draconic_block>, <draconicevolution:draconic_block>, <draconicevolution:draconic_block>, <draconicevolution:draconic_block>, <draconicevolution:draconic_block>, <draconicevolution:draconic_block>, <draconicevolution:draconic_block>, <draconicevolution:draconic_block>, <draconicevolution:draconic_block>], [<draconicevolution:draconic_block>, <avaritia:resource:5>, <additional_addons:catalyst1>, <additional_addons:catalyst1>, <avaritia:resource:5>, <additional_addons:catalyst1>, <additional_addons:catalyst1>, <avaritia:resource:5>, <draconicevolution:draconic_block>],[<draconicevolution:draconic_block>, <additional_addons:catalyst1>, <avaritia:resource:5>, <avaritia:resource:5>, <additional_addons:catalyst1>, <avaritia:resource:5>, <avaritia:resource:5>, <additional_addons:catalyst1>, <draconicevolution:draconic_block>],[<draconicevolution:draconic_block>, <avaritia:resource:5>, <additional_addons:catalyst1>, <additional_addons:catalyst1>, <avaritia:resource:5>, <additional_addons:catalyst1>, <additional_addons:catalyst1>, <avaritia:resource:5>, <draconicevolution:draconic_block>],[<draconicevolution:draconic_block>, <draconicevolution:draconic_block>, <draconicevolution:draconic_block>, <draconicevolution:draconic_block>, <draconicevolution:draconic_block>, <draconicevolution:draconic_block>, <draconicevolution:draconic_block>, <draconicevolution:draconic_block>, <draconicevolution:draconic_block>],[null, null, null, null, null, null, null, null, null],[null, null, null, null, null, null, null, null, null],[null, null, null, null, null, null, null, null, null],[null, null, null, null, null, null, null, null, null]]);

// Chaotic Infinity Ingot
recipes.remove(<additional_addons:chaoticinfinityingot>);
mods.avaritia.ExtremeCrafting.addShaped("HHAWENAMEPLACEHOLDER", <additional_addons:chaoticinfinityingot> * 1, [[<avaritia_neutronium_addon:neutroniumunstableingot>, <avaritia_neutronium_addon:neutroniumunstableingot>, <avaritia_neutronium_addon:neutroniumunstableingot>, <avaritia_neutronium_addon:neutroniumunstableingot>, <avaritia_neutronium_addon:neutroniumunstableingot>, <avaritia_neutronium_addon:neutroniumunstableingot>, <avaritia_neutronium_addon:neutroniumunstableingot>, <avaritia_neutronium_addon:neutroniumunstableingot>, <avaritia_neutronium_addon:neutroniumunstableingot>], [<avaritia_neutronium_addon:neutroniumunstableingot>, <additional_addons:chaoticingot>, <avaritia:resource:6>, <avaritia:resource:6>, <additional_addons:chaoticingot>, <avaritia:resource:6>, <avaritia:resource:6>, <additional_addons:chaoticingot>, <avaritia_neutronium_addon:neutroniumunstableingot>],[<avaritia_neutronium_addon:neutroniumunstableingot>, <avaritia:resource:6>, <additional_addons:chaoticingot>, <additional_addons:chaoticingot>, <additional_addons:ultimatebooster>, <additional_addons:chaoticingot>, <additional_addons:chaoticingot>, <avaritia:resource:6>, <avaritia_neutronium_addon:neutroniumunstableingot>],[<avaritia_neutronium_addon:neutroniumunstableingot>, <additional_addons:chaoticingot>, <avaritia:resource:6>, <avaritia:resource:6>, <additional_addons:chaoticingot>, <avaritia:resource:6>, <avaritia:resource:6>, <additional_addons:chaoticingot>, <avaritia_neutronium_addon:neutroniumunstableingot>],[<avaritia_neutronium_addon:neutroniumunstableingot>, <avaritia_neutronium_addon:neutroniumunstableingot>, <avaritia_neutronium_addon:neutroniumunstableingot>, <avaritia_neutronium_addon:neutroniumunstableingot>, <avaritia_neutronium_addon:neutroniumunstableingot>, <avaritia_neutronium_addon:neutroniumunstableingot>, <avaritia_neutronium_addon:neutroniumunstableingot>, <avaritia_neutronium_addon:neutroniumunstableingot>, <avaritia_neutronium_addon:neutroniumunstableingot>],[null, null, null, null, null, null, null, null, null],[null, null, null, null, null, null, null, null, null],[null, null, null, null, null, null, null, null, null],[null, null, null, null, null, null, null, null, null]]);

